images:
  repository: gcr.io/google-samples/microservices-demo
  tag: v0.9.0

frontend:
  name: frontend
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  service:
    type: ClusterIP
    ports:
      name: http
      sourcePort: 80
      targetPort: 80
  externalService:
    type: LoadBalancer
    ports:
      name: http
      sourcePort: 80
      targetPort: 8080

emailService:
  name: emailservice
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits: 
      cpu: 200m
      memory: 128Mi
  service:
    type: ClusterIP
    ports:
      name: grpc
      sourcePort: 5000
      targetPort: 8080

productCatalogService:
  name: productcatalogservice
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  service:
    type: ClusterIP
    ports:
      name: grpc
      sourcePort: 3550
      targetPort: 3550

currencyService:
  name: currencyservice
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  service:
    type: ClusterIP
    ports:
      name: grpc
      sourcePort: 7000
      targetPort: 7000

cartService:
  name: cartservice
  resources:
    requests:
      cpu: 200m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 128Mi
  service:
    type: ClusterIP
    ports:
      name: grpc
      sourcePort: 7070
      targetPort: 7070

recommendationService:
  name: recommendationservice
  resources:
    requests:
      cpu: 100m
      memory: 220Mi
    limits:
      cpu: 200m
      memory: 450Mi
  service:
    type: ClusterIP
    ports:
      name: grpc
      sourcePort: 8080
      targetPort: 8080 

shippingService:
  name: shippingservice

checkoutService:
  name: checkoutService

adService:
  name: adservice

paymentService:
  name: paymentservice

loadGenerator:
  name: loadgenerator