apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adService.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.adService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.adService.name }}
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: "{{ .Values.images.repository }}/{{ .Values.adService.name }}:{{ .Values.images.tag }}"
        ports:
        - containerPort: {{ .Values.adService.service.ports.targetPort }}
        env:
        - name: PORT
          value: "{{ .Values.adService.service.ports.targetPort }}"
        resources:
          requests:
            cpu: {{ .Values.paymentService.resources.requests.cpu }}
            memory: {{ .Values.paymentService.resources.requests.memory }}
          limits:
            cpu: {{ .Values.paymentService.resources.limits.cpu }}
            memory: {{ .Values.paymentService.resources.limits.memory }}
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: {{ .Values.adService.service.ports.targetPort }}
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: {{ .Values.adService.service.ports.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.paymentService.name }}
spec:
  type: {{ .Values.paymentService.service.type }}
  selector:
    app: {{ .Values.paymentService.name }}
  ports:
  - name: {{ .Values.paymentService.service.ports.name }}
    port: {{ .Values.paymentService.service.ports.sourcePort }}
    targetPort: {{ .Values.paymentService.service.ports.targetPort }}