apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.currencyService.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.currencyService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.currencyService.name }}
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.9.0
        ports:
        - name: grpc
          containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          grpc:
            port: 7000
        livenessProbe:
          grpc:
            port: 7000
        resources:
          requests:
            cpu: {{ .Values.currencyService.resources.requests.cpu }}
            memory: {{ .Values.currencyService.resources.requests.memory }}
          limits:
            cpu: {{ .Values.currencyService.resources.limits.cpu }}
            memory: {{ .Values.currencyService.resources.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.currencyService.name }}
spec:
  type: {{ .Values.currencyService.service.type }}
  selector:
    app: {{ .Values.currencyService.name }}
  ports:
  - name: {{ .Values.currencyService.service.ports.name }}
    port: {{ .Values.currencyService.service.ports.sourcePort }}
    targetPort: {{ .Values.currencyService.service.ports.targetPort }}